# NEON POOLED CONNECTION
spring.datasource.url=jdbc:postgresql://ep-restless-snow-and6t87b-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_T7EBrgFVPHp4
spring.datasource.driver-class-name=org.postgresql.Driver

# HIKARI POOL SETTINGS
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# AUTHENTICATION (Supabase)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://lhvrbtxqnsvnrallqaif.supabase.co/auth/v1
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://lhvrbtxqnsvnrallqaif.supabase.co/auth/v1/.well-known/jwks.json